### ISSUE TITLE
[Question] TikTok SlideshowOptions

### ISSUE THREAD

**Issue by Laiteux** [0x464e/slideshow-video#1]
Hey!

First of all thanks for this project, seems exactly like what we needed to replicate TikTok slideshows, and judging by the README it seems like that was your use case too (:

So, regarding that, I wanted to ask if you already had the exact `SlideshowOptions` to replicate TikTok slideshows figured out?

If so, could you please provide those? Or are these, by any chance, the ones you use in your README example?

```ts
const options: SlideshowOptions = {
    imageOptions: {
        imageDuration: 3500
    },
    transitionOptions: {
        transitionDuration: 500
    }
};
```

Seems like you're using different [default options](https://github.com/0x464e/slideshow-video/blob/master/src/util.ts#L105-L140) too, so I thought I'd ask and make sure. Hopefully this issue will also serve as a reference for others in the future.

Thanks a lot!

**Comment by 0x464e** [comment]
Hi, I'm very glad to see someone is finding this already.  
And funnily enough, I haven't actually set this up to my TikTok bot yet. Haven't had time haha. I've just tested it locally with a quick script to create videos. When I tested, I used 3 sec images and 250ms transitions. It was just what seemed sensible to me. But I'll probably be tweaking those settings once I actually put this into production to my TikTok bot.

But I did just now time to TikTok web ui for their timings. And it seems they display the image for ~1.8sec and transition takes ~750ms. And the timing seems to also be the same on my phone (Android). 1.8sec seems way too little for me, so I definitely won't be using that. But if you really want to replicate TikTok as closely as possible, that seems like that number to me.

Also, please be sure to create an issue about any bugs or problems you find. I have no doubt there are some bugs and issues left. It's hard to find everything since there's an endless combination of possible image and audio durations. I was planning on ironing out the kinks once I get this into my TikTok bot and then can see what goes wrong.

**Comment by Laiteux** [comment]
Thank you very, very much! (:
